// swift-tools-version: 6.1
// GENERATED by .github/workflows/publish.yml — do not edit by hand.
// Source: BoundaryML/baml @ 97252d5a48ee3d46448e173dc304fe8687926188 (canonical version 0.15.0)
import PackageDescription

let package = Package(
    name: "baml-swift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "BamlBridge", targets: ["BamlBridge"])
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.0")
    ],
    targets: [
        .binaryTarget(
            name: "BamlBridgeFFI",
            url: "https://github.com/BoundaryML/baml-swift/releases/download/dev-0.15.0-97252d5a48ee/BamlBridgeFFI-dev-0.15.0-97252d5a48ee.xcframework.zip",
            checksum: "7a76b5f097991423c8b5caebc93f668188a08e276b8d71a9b860ab8622ea9aa1"
        ),
        .target(
            name: "BamlBridge",
            dependencies: [
                "BamlBridgeFFI",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            linkerSettings: [
                // System deps of the Rust staticlib (TLS roots, DNS, CF).
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
                .linkedLibrary("resolv"),
            ]
        ),
    ]
)
