// swift-tools-version: 6.1
// GENERATED by .github/workflows/publish.yml — do not edit by hand.
// Source: BoundaryML/baml @ 86ce7ed0bf8184b847eeb5f77a84762ca9e1c1bd (canonical version 0.15.0)
import PackageDescription

let package = Package(
    name: "baml-swift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "BamlBridge", targets: ["BamlBridge"])
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.0")
    ],
    targets: [
        .binaryTarget(
            name: "BamlBridgeFFI",
            url: "https://github.com/BoundaryML/baml-swift/releases/download/dev-0.15.0-86ce7ed0bf81/BamlBridgeFFI-dev-0.15.0-86ce7ed0bf81.xcframework.zip",
            checksum: "e29b350388628cc10d6b0b50d5764e0ce7ad2ba0f330077b1b94562fac9b0b54"
        ),
        .target(
            name: "BamlBridge",
            dependencies: [
                "BamlBridgeFFI",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            linkerSettings: [
                // System deps of the Rust staticlib (TLS roots, DNS, CF).
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
                .linkedLibrary("resolv"),
            ]
        ),
    ]
)
