// swift-tools-version: 6.1
// GENERATED by .github/workflows/publish.yml — do not edit by hand.
// Source: BoundaryML/baml @ 63367b16f38a1f31f70a0302906f8a0c1280b0c7 (canonical version 0.15.0)
import PackageDescription

let package = Package(
    name: "baml-swift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "BamlBridge", targets: ["BamlBridge"])
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.0")
    ],
    targets: [
        .binaryTarget(
            name: "BamlBridgeFFI",
            url: "https://github.com/BoundaryML/baml-swift/releases/download/dev-0.15.0-63367b16f38a/BamlBridgeFFI-dev-0.15.0-63367b16f38a.xcframework.zip",
            checksum: "40338eb39071ab946034ad89299660458b58d77f7329b51d54ed4a7d6ba89e08"
        ),
        .target(
            name: "BamlBridge",
            dependencies: [
                "BamlBridgeFFI",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            linkerSettings: [
                // System deps of the Rust staticlib (TLS roots, DNS, CF).
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
                .linkedLibrary("resolv"),
            ]
        ),
    ]
)
